#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  echo "Usage: $(basename ${0}) <input> <output>"
  exit 1
fi

echo "Input: ${1}"
echo "Output: ${2}"

ffmpeg -y -i ${1} \
    -r 10 -s 176x144 -vb 400k \
    -acodec aac -strict experimental -ac 1 -ar 8000 -ab 24k \
    ${2}
